### ISSUE TITLE
404 on hoodie start in windows

### ISSUE THREAD

**Issue by kk3399** [zoepage/codequiz#3]
In windows, when I do `hoodie start`, this is the response I get for a request to `WWW` URL. I could start a testapp and get a proper response. Couldn't figure out why its throwing 404, any idea?
`{
statusCode: 404,
error: "Not Found"
}`

I didn't change anything in the repo, just installed dependencies and tried to run.
I could get the app to load fine in a Mac.

Thanks!

**Comment by zoepage** [comment]
so, the app is running?
did you start the angular plugin before the hoodie start?

**Comment by kk3399** [comment]
Hoodie app seem to be running. Is there any debug mode or anything as such, where I could trace any app start up errors?
I see message 'All plugins started' and 'hoodie-plugin-angularjs' is listed as Starting.

**Comment by zoepage** [comment]
Try 
$ hoodie start -v

**Comment by zoepage** [comment]
But it looks like the app can't find the angularjs app folder.. 

cc @elmarburke
